### ISSUE TITLE
[Sheet v2] Allow for customization of sections within panes

### ISSUE THREAD

**Issue by dm-colin** [mythmancer/mythmancer.github.io#157]
The current design is composed of three primary content panes which are each a vertical list of "sections".

A section is composed of logically grouped content i.e. "Ability Scores", "Weapons & Attacks" and so on.

On the page, there can be 3 panes active, but there ought to eventually be 2+ pages of panes to account for all of the possible character data; though discussion on that can be for another issue.

On a per-character basis, there ought to be a way to customize what sections are on what panes. That way if a player has determined that their Spellbook for example is important enough to be on the first page but maybe not their weapon attacks, they would have that ability.

**Comment by purajit** [comment]
Moved to https://github.com/orgs/mythmancer/projects/2/views/2

**Comment by purajit** [comment]
Moved to https://github.com/orgs/mythmancer/projects/2/views/2
